### ISSUE TITLE
Stabs are too short for SA profile keys w/ Realforce 87U

### ISSUE THREAD

**Issue by connor4312** [rixtox/Topre-to-Cherry-MX-Adapter#1]
I got four stabilizer from Shapeways for my 87U with PuLSE SA keycaps. Unfortunately it seems the stems are too short. When placing the keycaps from the top, they're wobbly and come off easily. With enough force they "stick", but go down too far and actuation is prevented. I tried taking apart the board and pushing the caps on the stabilizers from the bottom, but the same actuation problem occurred.

**Comment by rixtox** [comment]
Do you mean the plungers are easy to come off from the keycap stems? Did you follow the installation instructions on the stabilizer's Shapeways page? The order of the procedures are important.

**Comment by connor4312** [comment]
Sorry, yes, this is for the 2.25U plungers, not the spacebar stabilizers. I followed the instructions insofar as getting them printed in frosted ultra detail. For the other keys I used [1upkeyboard's topre-mx sliders](https://1upkeyboards.com/topre-mx-sliders.html) which were about 1-2mm taller than these plungers and fit fine.

**Comment by rixtox** [comment]
Oh I see. I use the word "stabilizers" mainly to refer the pair of space bar stabilizers. If you are talking about the 2.25u adapters, yes things may get complicated. The adapter behaves differently on 2.25u keycaps from different manufactures. As their stem diameters and the tightness of the stems varies from 1u to 2.25u, and each manufacture has its own specification, and usually not publicly available. I only have access and measured some keycaps I had available, so what I did was to make the inner diameter of the adapter's stem a bit wider to ensure most keycaps can fit into the hole, but it might lead to some keycaps a bit wobbly. A dirty fix of the problem is to stuck a piece of thin paper into the adapter plunger hole, making the inner diameter smaller. The best solution is to measure the diameter of your keycap's stem with digital vernier caliper. Then change the inner diameter in the CAD and reprint it to fit your need.

**Comment by connor4312** [comment]
Ok, thanks for the advice 😄 Just wanted to make sure I wasn't doing something wrong. I might try making 87U versions if I ever get some free time, and submit a PR with the updated models if it ends up working out.

For the moment though it might make sense to toss a note in the readme that the plungers are incompatible with the 87U keyboards.

**Comment by rixtox** [comment]
You are more than welcome to submit a PR. Thanks for helping to improve this project! README was just updated.
